export const SET_SEARCH_MOVIES = 'SET_SEARCH_MOVIES';
export const SET_EMPTY_SEARCH_MOVIES = 'SET_EMPTY_SEARCH_MOVIES';
export const SET_TOTAL_MOVIES = 'SET_TOTAL_MOVIES';
export const SET_COUNT_SEARCH_PAGE = 'SET_COUNT_SEARCH_PAGE';
export const SET_IS_SEARCHING = 'SET_IS_SEARCHING';
export const SET_IS_SEARCHING_LOADER_ACTIVE = 'SET_IS_SEARCHING_LOADER_ACTIVE';
export const SET_QUERY_VALUE = 'SET_QUERY_VALUE';
