export const SET_CHECKED_GENRES = 'SET_CHECKED_GENRES';
export const SET_CHECKED_YEARS = 'SET_CHECKED_YEARS';
export const SET_IS_OPEN_FILTER_POPUP = 'SET_IS_OPEN_FILTER_POPUP';
export const SET_IS_OPEN_CREW_POPUP = 'SET_IS_OPEN_CREW_POPUP';