export const SET_MOVIE_INFO = 'SET_MOVIE_INFO';
export const SET_MOVIE_CAST = 'SET_MOVIE_CAST';
export const SET_CURRENT_LOCATION_PATH = 'SET_CURRENT_LOCATION_PATH';
export const SET_RECOMMENDATION_MOVIES = 'SET_RECOMMENDATION_MOVIES';

