export const SET_MOVIE_INFO = 'SET_MOVIE_INFO';
export const SET_MOVIE_CAST = 'SET_MOVIE_CAST';
export const SET_IS_MOVIE_INFO_PAGE = 'SET_IS_MOVIE_INFO_PAGE';
export const SET_CURRENT_LOCATION_PATH = 'SET_CURRENT_LOCATION_PATH';

