export const SET_CURRENT_SORT_BY = 'SET_CURRENT_SORT_BY';
export const SET_IS_FILTERING = 'SET_IS_FILTERING';
export const SET_CHECKED_GENRES = 'SET_CHECKED_GENRES';
export const SET_CHECKED_YEARS = 'SET_CHECKED_YEARS';